# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).on 'turbolinks:load', ->
  $('#btn1').click ->
    alert 'this is alert'
    return
  return

# ---
# generated by js2coffee 2.2.0